### GET TO /client/deliveries
GET http://localhost:3000/client/deliveries HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhbWFsaG8iLCJpYXQiOjE2ODAzNzU4ODgsImV4cCI6MTY4MDQ2MjI4OCwic3ViIjoiMSJ9.h6W2N2TF3IMV2Pdx44FS7wIB8bZnL9Jz2rhLfSKWaAY
